apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sre-atlas
  namespace: wiki
  labels:
    app: sre-atlas
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - wiki.tentative.me
      secretName: sre-atlas-tls
  rules:
    - host: wiki.tentative.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sre-atlas
                port:
                  number: 80
