apiVersion: v1
kind: Service
metadata:
  name: sre-atlas
  namespace: wiki
  labels:
    app: sre-atlas
spec:
  selector:
    app: sre-atlas
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  type: ClusterIP
